# Generated by Django 5.0 on 2024-01-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='profile_pic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
